version: '3'

services:

  nginx:

      build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
      image: nginx
      ports:
          - '443:443'
      depends_on:
          - mariadb
          - wordpress
      volumes:
          - wordpress_volume:/var/www/html
      container_name: nginx
      restart: always
      networks:
        - inception_network

  wordpress:

      build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
      image: wordpress
      depends_on:
          - mariadb
      volumes:
          - wordpress_volume:/var/www/html
      environment:
          - MYSQL_DATABASE=${DATABASE_NAME}
          - MYSQL_USER=${DATABASE_USER}
          - MYSQL_USER_PASS=${DATABASE_USER_PASS}
          - MYSQL_HOST=${DATABASE_HOST}
          - MYSQL_ADMIN_USER=${WORDPRESS_ADMIN_USER}
          - MYSQL_ADMIN_USER_PASS=${WORDPRESS_ADMIN_USER_PASS}
      container_name: wordpress
      restart: always
      networks:
        - inception_network

  mariadb:

    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_USER_PASS=${DATABASE_USER_PASS}
      - MYSQL_ROOT_PASS=${MYSQL_ROOT_PASS}
    container_name: mariadb
    restart: always
    networks:
      - inception_network

networks:
  inception_network:
    driver: bridge

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/eamar/data/database
      o: bind
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/eamar/data/site
      o: bind
