From debian:buster

RUN apt-get update -y \
&& apt install nginx -y \
&& nginx

# ?
#ADD . /app/

#WORKDIR ...

#RUN ...

#EXPOSE 80

#repertoire partage avec host
#VOLUME /...

CMD ["nginx", "-g", "daemon off;"]
