version: '3'

services:

  nginx:

      build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
      ports:
          - '80:80'
          - '443:443'
      volumes:
        - ./data/site:/var/www/html/

      restart: always
      container_name: nginxC
      networks:
        - testnetwork

#  depends on ...

  wordpress:

      build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
          #supprimer ports ?
      ports:
          - '9000:9000'
      depends_on:
          - mariadb
      volumes:
          - ./data/site:/var/www/html/
      environment:
          - MYSQL_DATABASE=${DATABASE_NAME}
            #     - WORDPRESS_DB_HOST=mariadb
            #     - WORDPRESS_DB_USER=tobi
            #     - WORDPRESS_DB_PASSWORD=pass
            #     - WORDPRESS_DB_NAME=datata
            #     - WORDPRESS_TABLE_PREFIX=wp_
      container_name: wordpress
      restart: always
      networks:
        - testnetwork

  mariadb:

    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
        #supprimer ports ?
    ports:
      - '3306:3306'
        # utilisation du volume ?
    volumes:
      - ./data/database:/mariabase/
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
        #-  MYSQL_DATABASE=datata
        #   -  MYSQL_ROOT_PASSWORD=pass
        #   -  MYSQL_USER=tobi
        #   -  MYSQL_PASSWORD=pass
        #     #- MYSQL_ROOT_PASSWORD=pass
    container_name: mariadb
      #remettre mariadbC
    networks:
      - testnetwork
    restart: always
  
#  mysql:
#      image: mariadb
#      ports:
#          - '3306:3306'
#      volumes:
#          - ./db-data:/var/lib/mysql
#      environment:
#          - MYSQL_ROOT_PASSWORD=Strong password
#      restart: always
#      networks:
#        - testnetwork

networks:
  testnetwork:
