version: '3'

services:

  nginx:

      build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
        args:
          DOMAIN_NAME: ${DOMAIN_NAME}
        #INUTILISE POUR L INSTANT, UTILISER ??-> MODIFIER /etc/hosts ??
      ports:
          - '80:80'
          - '443:443'
      volumes:
        - /home/eamar/data/site:/var/www/html/

      restart: always
      container_name: nginxC
      networks:
        - inception_network

#  depends on ...

  wordpress:

      build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
          #supprimer ports ?
      ports:
          - '9000:9000'
      depends_on:
          - mariadb
      volumes:
          - /home/eamar/data/site:/var/www/html/
      environment:
          - MYSQL_DATABASE=${DATABASE_NAME}
          - MYSQL_USER=${DATABASE_USER}
          - MYSQL_USER_PASS=${DATABASE_USER_PASS}
          - MYSQL_HOST=${DATABASE_HOST}
          - MYSQL_ADMIN_USER=${DATABASE_ADMIN_USER}
          - MYSQL_ADMIN_USER_PASS=${DATABASE_ADMIN_USER_PASS}
            #     - WORDPRESS_TABLE_PREFIX=wp_
      container_name: wordpress
      restart: always
      networks:
        - inception_network

  mariadb:

    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        MYSQL_DATABASE: ${DATABASE_NAME}
        MYSQL_USER: ${DATABASE_USER}
        MYSQL_USER_PASS: ${DATABASE_USER_PASS}
    ports:
      - '3306:3306'
        # utilisation du volume ?
    volumes:
      - ./data/database:/mariabase/
        # Que faire pour le volume
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
        #mettre un root password
      #-  MYSQL_ROOT_PASSWORD=pass
      #- MYSQL_ROOT_PASSWORD=pass
    container_name: mariadb
      #remettre mariadbC
    restart: always
    networks:
      - inception_network

networks:
  inception_network:
#Que se passe t il quand on ne precise rien ici
