version: '3'

services:

  camembert:

      build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
      ports:
          - '80:80'
      volumes:
        - ./data/site:/var/www/html/

      restart: always
      container_name: container_nginx
      networks:
        - testnetwork

#  depends on ...

  wordy:

      build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
      ports:
          - '9000:9000'
      volumes:
      - ./data/site:/var/www/html/
          #environment:
          #    - WORDPRESS_DB_NAME=name
          #    - WORDPRESS_TABLE_PREFIX=wp_
          #    - WORDPRESS_DB_HOST=mysql
          #    - WORDPRESS_DB_PASSWORD=pass
            #links:
            #- mysql
      container_name: container_wordy
      restart: always
      networks:
        - testnetwork
  
#  mysql:
#      image: mariadb
#      ports:
#          - '3306:3306'
#      volumes:
#          - ./db-data:/var/lib/mysql
#      environment:
#          - MYSQL_ROOT_PASSWORD=Strong password
#      restart: always
#      networks:
#        - testnetwork

networks:
  testnetwork:
