#!/bin/bash

service mysql start

if [ ! -e "/var/lib/mysql/$MYSQL_DATABASE" ]; then

mysql -e "CREATE DATABASE $MYSQL_DATABASE;"

else
	echo database is already present, creation step skipped
fi

mysql -u root -p$MYSQL_ROOT_PASS -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASS';"

mysql -u root -p$MYSQL_ROOT_PASS -e "GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_USER'@'wordpress.srcs_inception_network' IDENTIFIED BY '$MYSQL_USER_PASS' WITH GRANT OPTION;"

mysql -u root -p$MYSQL_ROOT_PASS -e "FLUSH PRIVILEGES;"

service mysql stop

kill $(cat /var/run/mysqld/mysqld.pid)

mysqld
