#!/bin/bash

service mysql start

if [ ! -e "/var/lib/mysql/$MYSQL_DATABASE" ]; then

mysql -e "CREATE DATABASE $MYSQL_DATABASE;"

else
	echo database is already present, creation step skipped
fi

mysql -e "GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_USER'@'wordpress.srcs_inception_network' IDENTIFIED BY '$MYSQL_USER_PASS' WITH GRANT OPTION;"
mysql -e "FLUSH PRIVILEGES;"

service mysql stop

mysqld
