#!/bin/bash

#apt-get install mariadb-server -y

service mysql start

mysql -e "CREATE DATABASE $MYSQL_DATABASE;"

mysql -e "GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_USER'@'wordpress.srcs_inception_network' IDENTIFIED BY '$MYSQL_USER_PASS' WITH GRANT OPTION;"
mysql -e "FLUSH PRIVILEGES;"

service mysql stop

mysqld
