#!/bin/bash

if [ ! -e "/var/www/html/wp-config.php" ]; then

wp core download --path=/var/www/html --allow-root

wp config create --path=/var/www/html --dbname=$MYSQL_DATABASE --dbuser=$MYSQL_USER --dbpass=$MYSQL_USER_PASS --dbhost=$MYSQL_HOST --allow-root


wp core install --path=/var/www/html --url="eamar.42.fr" --title="elephant de grabouilli" --admin_user=$MYSQL_ADMIN_USER --admin_password=$MYSQL_ADMIN_USER_PASS --admin_email=elon.musk@yahoo.fr --allow-root

else
	echo Wordpress already installed, installation step skipped
fi

php-fpm7.3 -F -R
